#pragma once

enum {
    KERR_PAGE_ALLOC_INIT_FAILURE=0,
    KERR_ALLOC_INIT_FAILURE=1,
    KERR_SCHEDULER_OVERFLOW=2,
    KERR_INPUT_LISTENERS_OVERFLOW=3,
    KERR_ENV_INIT_ERROR=4,
    KERR_NO_SHELL=5,
    KERR_NO_PAGE_MEMORY=6,
};
